OPTIONS (skip=1)
LOAD DATA
INFILE "/dw-data/AICS/testcsv/tprojectinfo.csv"
truncate
INTO TABLE AICS_PROJECT_INFO
fields terminated by "^*"
Optionally enclosed by '"'
trailing nullcols
(
  virtual_colum FILLER,
  projectcode            ,
  projectname            ,
  projectnature          ,
  projectphase           ,
  risktype               ,
  fdcbusitype            ,
  projectstatus          ,
  dptid                  ,
  depcode                ,
  assetseller            ,
  servicebank            ,
  moneytype              ,
  predictinvestdate      DATE"YYYY-MM-DD HH24:MI:SS" ,
  trustmanager           ,
  projectteammembers     ,
  isperfectturnstock     ,
  durdiligencelaunchorg  ,
  pshorgno               ,
  amccustomerno          ,
  framesignedmoney       ,
  applyinvestmoney       ,
  producttype            ,
  financingname          ,
  belongtoindustry       ,
  companynature          ,
  creditrating           ,
  istraded               ,
  registeredcapital      ,
  locatedarea            ,
  predebtratio           ,
  afterdebtratio         ,
  extfield10             ,
  predictinvestlimit     ,
  investintentmemo       char(4000),
  channelcostmemo        ,
  fundtrustee            ,
  isneeddirector         ,
  isneedsupervisor       ,
  droptype               ,
  dropdescribe           char(4000),
  predictyield           ,
  predictyieldexplain    char(4000),
  debtsum                ,
  debtcorpusamount       ,
  debtinterest           ,
  applyowninvestmoney    ,
  isleavedebt            ,
  leavedebtmoney         ,
  leavedebtdescribe      ,
  investedcompany        ,
  financialproducttype   ,
  financialproductcode   ,
  prebalancesum          ,
  timelimit              ,
  distributionmode       ,
  stockpremiumrate       ,
  initstockprice         ,
  parvaluerate           ,
  redeemprice            ,
  exchagnestockbeginday  DATE"YYYY-MM-DD HH24:MI:SS" ,
  initpledgerate         ,
  additionalguarantee    ,
  lowrepairclause        ,
  redemptionclause       ,
  resaleclause           ,
  isintermechanism       ,
  servicecontentdescribe char(5000),
  investtarget           char(5000),
  capital                char(5000),
  framework              char(5000),
  partyinfo              char(5000),
  tasset                 char(5000),
datadate  "(select data_date from etl_control.ctl_general_parameter)",
etl_date "sysdate "
)
