OPTIONS (skip=1)
LOAD DATA
INFILE "/dw-data/AICS/testcsv/tasset_loanaccount_info.csv"
truncate
INTO TABLE AICS_ASSET_LOANACCOUNT_INFO
fields terminated by "^*"
Optionally enclosed by '"'
trailing nullcols
(
  virtual_colum FILLER,
  loanaccountcode        ,
  loanaccountnum         ,
  loanaccountname        ,
  loanstatus             ,
  projectcode            ,
  industrydetail         ,
  provincecode           ,
  cityno                 ,
  regioncode             ,
  businesscondition      ,
  corpusamount           ,
  interest               ,
  disbursementfee        ,
  minquotedprice         ,
  maxquotedprice         ,
  loanaccountcosts       ,
  replayrate             ,
  memo                   ,
  enteruser              ,
  entertime              DATE"YYYY-MM-DD HH24:MI:SS" ,
  lastupdateuser         ,
  lastupdatetime         DATE"YYYY-MM-DD HH24:MI:SS" ,
  loanmanager            ,
  evaluationuser         ,
  reclaimscale           ,
  currentscale           ,
  quotationscale         ,
  disposalyears          ,
  balancecost            ,
  currentbalance         ,
  deductionten           ,
  lasttimeloss           ,
  lastbalance            ,
  qualification          ,
  issolvency             ,
  ispay                  ,
  lastamount             ,
  recoverablescale       ,
  recoverablebalancec    ,
  disposalmoney          ,
  lastbalanceall         ,
  abstract1              ,
  abstract2              ,
  abstract3              ,
  abstract4              ,
  abstract5              ,
  abstract6              ,
  abstract7              ,
  abstract8              ,
  abstract9              ,
  abstract10             ,
  setupdate              DATE"YYYY-MM-DD HH24:MI:SS" ,
  representative         ,
  registemoney           ,
  businesscope           ,
  address                ,
  cykind                 ,
  relationcode           ,
  opertorvaluationdate   DATE"YYYY-MM-DD HH24:MI:SS" ,
  transferbalance        ,
  fxassetrate            ,
  schemeid               ,
  isalldeal              ,
  assetsource            ,
  assetsourcename        ,
  abstract11             ,
  abstract12             ,
  predisposalperiod      ,
  defaultinterest        ,
  otherfee               ,
  subcompanyreceivedate  DATE"YYYY-MM-DD HH24:MI:SS" ,
  subcompanyreceivemoney ,
  litigationstatus       ,
  mindealprice           ,
  entertype              ,
  propertynature         ,
  escrowstatus           ,
  assetseller            ,
  baseday                DATE"YYYY-MM-DD HH24:MI:SS" ,
  margin_balance         ,
  recprecoverablescale   ,
  recprecoverablebalance ,
  asset_category         ,
  source                 ,
  is_continue_agency     ,
  continue_agency        ,
datadate  "(select data_date from etl_control.ctl_general_parameter)",
etl_date "sysdate "
)
